---
# task for updating timezone settings

- name: Remove existing localtime configuration file
  file: path=/etc/localtime state=absent

- name: Set localtime to Europe/Kiev
  file: src=/usr/share/zoneinfo/Europe/Kiev dest=/etc/localtime state=link owner=root group=root mode=0644

- name: Reconfigure tzdata
  command: dpkg-reconfigure -f noninteractive tzdata
